@baseUrl = http://localhost:3002
@json = application/json

GET {{baseUrl}}/tasks

### POST test
POST  {{baseUrl}}/tasks/create 
content-type: {{json}}

{ 
    "name": "Teste",
    "description": "teste description",
    "completed": false
}

### PATCH Test
PATCH {{baseUrl}}/tasks/2
content-type: {{json}}

{ 
    "name": "teste alterado"
}

### GET one by ID
GET {{baseUrl}}/tasks/2

### DELETE Test
DELETE {{baseUrl}}/tasks/2
content-type: {{json}}

{ 
    "name": "teste"
}
