@baseUrl = http://localhost:3000
@json = application/json

GET {{baseUrl}}/tasks

### POST test
POST  {{baseUrl}}/tasks/create 
content-type: {{json}}

{ 
    "name": "teste create",
    "description": "teste description",
    "completed": false
}

### PATCH Test
PATCH {{baseUrl}}/tasks/2
content-type: {{json}}

{ 
    "name": "teste alterado"
}

### DELETE Test
DELETE {{baseUrl}}/tasks/2
content-type: {{json}}

{ 
    "name": "teste"
}
