@baseUrl = http://localhost:3000
@json = application/json

GET {{baseUrl}}/tasks/2

### POST test
POST  {{baseUrl}}/tasks/create 
content-type: {{json}}

{ 
    "name": "teste"
}

### PATCH Test
PATCH {{baseUrl}}/tasks/2
content-type: {{json}}

{ 
    "name": "teste"
}

### DELETE Test
DELETE {{baseUrl}}/tasks/2
content-type: {{json}}

{ 
    "name": "teste"
}
